### ISSUE TITLE
Update to Nuxt3 (now that it's available)

### ISSUE THREAD

**Issue by pascalwengerter** [pentacent/keila-web#4]
Not sure if you're interested in that @wmnnd?

**Comment by wmnnd** [comment]
Do you want to take it on as a holiday project? :smiley:

**Comment by pascalwengerter** [comment]
> Do you want to take it on as a holiday project? 😃

Why not, could actuall be _fun_ ™️. I'll give it a look between Christmas and NYE

**Comment by wmnnd** [comment]
Yay! :christmas_tree: :santa: 

Except, of course, if you’d rather take a look at Astro to see if that might be an even better option. I find their approach of doing minimal client-side JS quite interesting and since it supports Vue, we could still retain a fair bit of the existing code.

**Comment by pascalwengerter** [comment]
> Yay! 🎄 🎅
> 
> Except, of course, if you’d rather take a look at Astro to see if that might be an even better option. I find their approach of doing minimal client-side JS quite interesting and since it supports Vue, we could still retain a fair bit of the existing code.

Already looking around the codebase a bit, not sure what you think of https://github.com/gohugoio/hugo but I'm a fan 😬 also already debugging the Nuxt3 update 🤦🏽 don't think it'll be a wild ride, fingers crossed

**Comment by wmnnd** [comment]
I’ve never worked with Hugo but if it’s stable and it could help get rid of some of the JavaScript complexities, I wouldn’t be mad about getting rid of Vue.

**Comment by pascalwengerter** [comment]
Closing since a relaunch on a different tech stack is planned (see https://github.com/pentacent/keila-web/pull/5#issuecomment-2109953621 for details)
